spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:KLxSIPqiu7_xzJrC61JXwiAbRRxq742fOHaUvKwMtGsxKUmv@a2a6a5d6-a233-4606-89da-babfe90e3d3c.asia-south1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}